language: python
services:
  - docker

python:
  - "2.7"

install:
  - make deps

script:
  - make test

after_success:
  - make docker_build
  - make docker_push
  - make test_xunit

deploy:
  provider: heroku
  app: radiant-escarpment-95515
  api_key: ${HEROKU_API_KEY}
