language: python
services:
  - docker

python:
  - "2.7"

install:
  - make deps

script:
  - make lint
  - make test
  - make docker_build
  - make docker_run
  - sleep 3; make test_api
  #- make test_ui


after_success:
  - make docker_push

deploy:
  provider: heroku
  app: radiant-escarpment-95515
  api_key: ${HEROKU_API_KEY}
